builds:
- id: github-rss
  main: ./cmd/github-rss
  goos:   [ linux ]
  goarch: [ amd64 ]
  flags:  [ -v ]
- id: gitorg-rss
  main: ./cmd/gitorg-rss
  goos:   [ linux ]
  goarch: [ amd64 ]
  flags:  [ -v ]
- id: gitissue-rss
  main: ./cmd/gitissue-rss
  goos:   [ linux ]
  goarch: [ amd64 ]
  flags:  [ -v ]
