.PHONY: all test build clean install testrun

all: test build
test:    ; go test -vet=all -v ./...
build:   ; go build -ldflags="-w -s" ./...
clean:   ; go clean -x ./...
install: ; go install -ldflags="-w -s" ./...
testrun:
	go run cmd/gitissue-rss/main.go 'https://github.com/azimut/github-rss/issues/1'
	go run cmd/gitorg-rss/main.go shirakumo
	go run cmd/github-rss/main.go azimut
