GO ?= /usr/bin/go

.PHONY: all test build clean install testrun

all: test build
test:    ; $(GO) vet ./... ; go test ./...
build:   ; $(GO) build -x -v ./...
clean:   ; $(GO) clean -x ./...
install: ; $(GO) install ./...
testrun:
	$(GO) run cmd/gitissue-rss/main.go 'https://github.com/azimut/github-rss/issues/1'
	$(GO) run cmd/gitorg-rss/main.go shirakumo
	$(GO) run cmd/github-rss/main.go azimut
